### ISSUE TITLE
On branch develope: Non wav files in ./Datasets/noise_filenames.json 

### ISSUE THREAD

**Issue by qqq89513** [ghnmqdtg/Deep-Learning-Based-Noise-Reduction-and-Speech-Enhancement-System#2]
## Version
Branch: develope
Commit: 0cb8622b397b4fb2440a46c3b96e88f8c0d6212c

## Description
`./Datasets/noise_filenames.json` should only has wav files as elements.
Instead, it seems like it list all the files under each directory.
```json
 "Verbal_Human": {
            "records": 700,
            "filenames": [
                "./Datasets/Audioset/unbalanced/Verbal_Human/as_download_unbalanced.py",
                "./Datasets/Audioset/unbalanced/Verbal_Human/labels.xlsx",
                "./Datasets/Audioset/unbalanced/Verbal_Human/unbalanced_train_segments.xlsx",
                "./Datasets/Audioset/unbalanced/Verbal_Human/audiosetdata/Babbling/snipped10736.wav",
```

## Possible fix
Skip the ones which file extensions are not _.wav_ .
In `./data_parser.py`, line 74:
```python
for filename in files:
    if filename.endswith('.wav') or filename.endswith('.WAV'):
        temp_list.append(f'{root}/{filename}'.replace("\\", "/"))
```

**Comment by ghnmqdtg** [comment]
Yep, although it will automatically be skipped and doesn't affect the mixing procedure of the audio, it's truly a mistake to parse the folder that contains unrelated files without filtering them out. I will fix it asap, thanks.
