### ISSUE TITLE
librosa.load() is super slow

### ISSUE THREAD

**Issue by qqq89513** [ghnmqdtg/Deep-Learning-Based-Noise-Reduction-and-Speech-Enhancement-System#3]
## Description
I found out the performance of loading dataset from wav files has no big improvement after I use batch load in f0ea1f5.
It turns out that the slow one is `librosa.load()`. In my environment, the following snippet shows that it takes about 300ms to load a wav file.
```python
t1 = time.time()
x, sr = librosa.load(filename)
t2 = time.time()
t2 - t1
```

## Version
Branch: noise_classifer
Commit: f0ea1f5a9b305ee977f3bd8fb8f16f085d2b0048
This problem is probably in every branch that needs to load wav files.

**Comment by qqq89513** [comment]
[This](https://newbedev.com/difference-between-load-of-librosa-and-read-of-scipy-io-wavfile) and [this](https://stackoverflow.com/questions/50062358/difference-between-load-of-librosa-and-read-of-scipy-io-wavfile) say that the reason that `librosa.load()` is slow is that it resample the audio by default. You can specify sample rate as `None` and `.load()` will not do the resampling.
```python
t1 = time.time()
x, sr = librosa.load(filename, sr=None)
t2 = time.time()
t2 - t1
```

**Comment by ghnmqdtg** [comment]
I've seen this problem before, batch processing may not bring you a shorter run time, but it does avoid running out of memory(OOM).

If you want it to be faster, maybe you can try:

1. Threading, but not that easy to develop.
2. Pre-save the loaded audio array into `.npy` file using numpy.save.

**Comment by qqq89513** [comment]
Oh I just solved it with a hacky way. Haven't pushed it yet.

ghnmqdtg ***@***.***> 於 2021年6月19日 週六 下午1:13 寫道：
